"""Добавить unique index для tg_id

Revision ID: 01fb4c7a5ce7
Revises: 4805d6bddab9
Create Date: 2026-01-18 21:18:40.918866

"""

from typing import Sequence, Union

from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01fb4c7a5ce7"
down_revision: Union[str, Sequence[str], None] = "4805d6bddab9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_users_tg_id", "users", ["tg_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_tg_id", "users", type_="unique")
    # ### end Alembic commands ###
