"""init

Revision ID: 6552ee056183
Revises: 
Create Date: 2026-02-21 14:34:40.030145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6552ee056183'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_identities',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('provider', sa.SmallInteger(), nullable=False),
    sa.Column('sub', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_identities_user_id_fk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'sub', name='user_identities_provider_sub_ux'),
    sa.UniqueConstraint('user_id', 'provider', name='user_identities_user_provider_ux')
    )
    op.create_index('user_identities_user_id_ix', 'user_identities', ['user_id'], unique=False)
    op.create_table('tokens',
    sa.Column('token_hash', postgresql.BYTEA(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idp_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['idp_id'], ['user_identities.id'], name='tokens_user_idp_id_fk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tokens_user_id_fk'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_index('user_identities_user_id_ix', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_table('users')
    # ### end Alembic commands ###
